name: barteron.club

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: [ barteron.club ]
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Prepare
        run: |
          npm install --global yarn
          yarn install
          yarn build
      - name: Copy
        run: |
          rm -rf /data/barteron/*
          rsync -ah ./dist/ /data/barteron/
        
  build-mirror:
    runs-on: [ mirror.barteron.club ]
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Prepare
        run: |
          npm install --global yarn
          yarn install
          yarn build
      - name: Copy
        run: |
          rm -rf /data/barteron/*
          rsync -ah ./dist/ /data/barteron/
