name: test.barter.pocketnet.app

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: test
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Prepare
        run: |
          npm install --global yarn
          yarn install
          yarn build
      - name: Copy
        run: |
          rm -rf /docker/barter/*
          rsync -ah ./dist/ /docker/barter/
        
